config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :questions, shallow: true do
    resources :answers do
      member do
        put 'like_dislike' => "answers#like_dislike"
      end
      resources :comments
    end
  end

  post 'users/profile_photo' => 'users#profile_photo'

  root to: "questions#index"
end

app/models/answer.rb
# frozen_string_literal: true

class Answer < ApplicationRecord
  validates :description, presence: true
  has_many :comments, dependent: :destroy
  belongs_to :question
  belongs_to :user

  acts_as_votable

  paginates_per 5
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  validates :description, presence: true
  belongs_to :user
  belongs_to :answer
end

app/models/question.rb
# frozen_string_literal: true

class Question < ApplicationRecord
  validates :title, :description, presence: true
  has_many :answers, dependent: :destroy
  belongs_to :user
  
  paginates_per 5
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  mount_uploader :profile_photo, ProfilePhotoUploader

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, :omniauth_providers => [:google_oauth2]

  acts_as_voter

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.token = auth.credentials.token
      user.expires = auth.credentials.expires
      user.expires_at = auth.credentials.expires_at
      user.refresh_token = auth.credentials.refresh_token
    end
  end

end

app/controllers/answers_controller.rb
# frozen_string_literal: true

class AnswersController < ApplicationController
  include AnswersHelper

  def create
    respond_to do |format|
      format.js
      format.html
    end

    question, answer = fetch_answers(params, answer_params)
    if answer.save
      questioner_email = question.user.email
      answerer_first_name = answer.user.first_name
      AnswerMailer.answered(questioner_email, answerer_first_name).deliver_now
      redirect_to question_path(params[:question_id])
    else
      render 'questions/show'
    end
  end

  private

  def answer_params
    params.require(:answer).permit(:description, :question_id)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :authenticate_user!, only: [:new, :create, :profile_photo]

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit({ roles: [] }, :email, :password, :password_confirmation, :first_name, :last_name) }
  end
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  def create
    respond_to do |format|
      format.js
      format.html
    end

    @answer = Answer.find(params[:answer_id])
    @comment = @answer.comments.new(comment_params)

    @comment.user_id = current_user.id
    if @comment.save!
      redirect_to question_path(params[:id])
    else
      render 'questions/show'
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:description, :answer_id)
  end
end

app/controllers/questions_controller.rb
# frozen_string_literal: true

class QuestionsController < ApplicationController
  include QuestionsHelper
  def index
    @total_questions = Question.count
    @questions = Question.order(created_at: :desc).page(params[:page])
  end

  def show
    @question, @answers, @answer, @active_answers, @oldest_answers, @answers_votes = question_and_answers(params)
  end

  def new
    @question = Question.new
  end

  def create
    @question = create_question(question_params)
    if @question.save
      redirect_to @question
    else
      render 'new'
    end
  end

  private

  def question_params
    params.require(:question).permit(:title, :description)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include UsersHelper
  
  skip_before_action :verify_authenticity_token

  def profile_photo
    user_profile_photo(params)
  end
end

app/helpers/answers_helper.rb
# frozen_string_literal: true

module AnswersHelper
  def fetch_answers(params, answer_params)
    question = Question.find(params[:question_id])
    answer = question.answers.new(answer_params)

    answer.user_id = current_user.id
    return question, answer
  end

  def like_dislike
    answer = Answer.find(params[:id])
    if params[:format] == 'like'
      answer.liked_by current_user
    elsif params[:format] == 'dislike'
      answer.disliked_by current_user
    end
    redirect_to :back
  end

  def answerer_name(answer)
    name = answer.user.first_name + answer.user.last_name
  end
  
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/comments_helper.rb
# frozen_string_literal: true

module CommentsHelper
  def commenter_name(comment)
    name = comment.user.first_name + comment.user.last_name
  end
end

app/helpers/questions_helper.rb
# frozen_string_literal: true

module QuestionsHelper
  def question_and_answers(params)
    question = Question.find(params[:id])
    answers = question.answers
    active_answers = question.answers.order(created_at: :desc).page params[:aactive_page]
    oldest_answers = question.answers.page params[:oldest_page]
    answers_votes = question.answers.order(votes_for: :asc).page params[:votes_page]
    answers.includes(:comments, :user).each do |a|
      @comment = a.comments.new
    end
    answer = answers.new
    return question, answers, answer, active_answers, oldest_answers, answers_votes
  end

  def create_question(question_params)
    question = Question.new(question_params)
    question.user_id = current_user.id
    question
  end

  def questioner_name(question)
    name = question.user.first_name + question.user.last_name
  end
end

app/helpers/users/omniauth_callbacks_helper.rb
# frozen_string_literal: true

module Users::OmniauthCallbacksHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def user_profile_photo(params)
    user = User.find(params[:id])
    user.profile_photo = params[:myFile]
    user.save!
    redirect_to edit_user_registration_path
  end
end

app/views/layouts/_footer.html.erb
<hr>
<footer class="footer">
    <div class="container">
      <!-- Footer -->
<footer class="page-footer font-small blue pt-4">

    <!-- Footer Links -->
    <div class="container-fluid text-center text-md-left">
  
      <!-- Grid row -->
      <div class="row">
        <!-- Grid column -->

        <hr class="clearfix w-100 d-md-none pb-3">
  
        <!-- Grid column -->
        <div class="col-md-3 mb-md-0 mb-3">
  
          <!-- Links -->
          <h5 class="text-uppercase">Links</h5>
  
          <ul class="list-unstyled">
            <li>
              <a href="#!">Link 1</a>
            </li>
            <li>
              <a href="#!">Link 2</a>
            </li>
            <li>
              <a href="#!">Link 3</a>
            </li>
            <li>
              <a href="#!">Link 4</a>
            </li>
          </ul>
  
        </div>
        <!-- Grid column -->
  
        <!-- Grid column -->
        <div class="col-md-3 mb-md-0 mb-3">
  
          <!-- Links -->
          <h5 class="text-uppercase">Links</h5>
  
          <ul class="list-unstyled">
            <li>
              <a href="#!">Link 1</a>
            </li>
            <li>
              <a href="#!">Link 2</a>
            </li>
            <li>
              <a href="#!">Link 3</a>
            </li>
            <li>
              <a href="#!">Link 4</a>
            </li>
          </ul>
  
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-3 mb-md-0 mb-3">
  
            <!-- Links -->
            <h5 class="text-uppercase">Links</h5>
    
            <ul class="list-unstyled">
              <li>
                <a href="#!">Link 1</a>
              </li>
              <li>
                <a href="#!">Link 2</a>
              </li>
              <li>
                <a href="#!">Link 3</a>
              </li>
              <li>
                <a href="#!">Link 4</a>
              </li>
            </ul>
    
          </div>
          <!-- Grid column -->

          <!-- Grid column -->
        <div class="col-md-3 mb-md-0 mb-3">
  
            <!-- Links -->
            <h5 class="text-uppercase">Links</h5>
    
            <ul class="list-unstyled">
              <li>
                <a href="#!">Link 1</a>
              </li>
              <li>
                <a href="#!">Link 2</a>
              </li>
              <li>
                <a href="#!">Link 3</a>
              </li>
              <li>
                <a href="#!">Link 4</a>
              </li>
            </ul>
    
          </div>
          <!-- Grid column -->
  
      </div>
      <!-- Grid row -->
  
    </div>
    <!-- Footer Links -->
  
    <!-- Copyright -->
    <div class="footer-copyright text-center py-3">
      <copyright>
        &copy; <%= Time.now.year %> Copyright:
        <a href="http://localhost:3000/"> StackOverflow.com</a> 
      </copyright>
    </div><hr>
    <!-- Copyright -->
  
  </footer>
  <!-- Footer -->      

app/views/layouts/_header.html.erb
<div class="navbar-fixed-top" id="nav_main">
  <div id="logo_image">
    <%= link_to image_tag("stackoverflow_logo.png", :size => '220x50'), "http://localhost:3000/" %>
  </div>
  <div id="nav_buttons">
    <% if user_signed_in? %>
      Welcome <strong><%= current_user.first_name %> <%= current_user.last_name %> | </strong>
      <%= link_to '<button class="btn btn-info" type="button">Edit profile</button>'.html_safe, edit_user_registration_path %> |
      <%= link_to '<button class="btn btn-danger" type="button">Logout</button>'.html_safe, destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to '<button class="btn btn-primary" type="button">Sign up</button>'.html_safe, new_user_registration_path %> |
      <%= link_to '<button class="btn btn-info" type="button">Login</button>'.html_safe, new_user_session_path %>
    <% end %>
  </div>
</div>
<br><br><br><br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StackOverflow</title>
    <%= favicon_link_tag 'stackoverflow_icon.png' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.2/css/all.css" integrity="sha384-/rXc/GQVaYpyDdyxK+ecHPVYJSN9bmVFBvjA/9eOB+pb3F2w2N6fc5qB9Ew5yIns" crossorigin="anonymous">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="main-body">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/questions/_answer_form.html.erb
<br><br><h3><b><u>Post Your Answer</u></b></h3><br>
<%= simple_form_for [@question, @answer], remote: true do |form| %>
  <p>
    <%= form.cktext_area :description, required: :true %>
  </p>
  <p>
    <%= form.submit "Post Your Answer", :class => "btn btn-success" %>
  </p>
<% end %><br><br>
<%= button_to "Back", questions_path, :class => "btn btn-info" %>

app/views/questions/_comment_form.html.erb
<center>
  <%= simple_form_for [answer, @comment], remote: true do |form| %>
      <p>
        <input name="id" type="hidden" value=<%= @question.id %>
        <h4><%= form.label :Comment %></h4><br>
        <%= form.text_area :description, :required => true, :class => "comment_text_area" %>
      </p>
    <p>
      <%= form.submit "Comment", :class => "btn btn-success" %>
    </p>
  <% end %>
</center>

app/views/questions/index.html.erb
<!DOCTYPE html>
<html>
  <head>
  </head>
  <body>
    <center>
      <h1><u>All Questions :-</u></h1><br>
      <%= button_to 'Ask Question', new_question_path, method: :get, class: "btn btn-primary" %><br><br>
      <h3><u>Total <%= @total_questions %> <%= @total_questions <= 1  ? 'Question' :  'Questions' %></u></h3>
      <br>
    </center>

    <div id="question_list"><hr>
      <% @questions.each do |question| %>
        <div class="question_box">
            <div class="box_row">
              <div class="box_cell box1">
                <h3 class="answers_counts"><%= question.answers.count %></h3>
                <h5 class="answers_counts">Answers</h5>
              </div>
              <div class="box_cell box2">
                <h3><%= link_to question.title, question_path(question) %></h3>
                <td><%= truncate(question.description.html_safe, length: 300) %></td>
              </div>
            </div>
        </div><hr>
      <% end %><hr>
    </div><br>

    <center><%= paginate @questions %></center>
  </body>
</html>

app/views/questions/new.html.erb
<html>
<head>
  <title>Stack Overflow</title>
</head>
<body>
  <br><br>
  <center>
    <h1>Ask a public question</h1><hr>
    <%= form_with scope: :question, url: questions_path, local: true do |form| %>
      <p>
        <%= form.label :title %><br>
        <%= form.text_field :title, :required => true, :id => "question_title_field" %>
      </p>
      <p>
        <%= form.label :description %><br>
        <%= form.cktext_area :description %>
      </p>
      <p>
        <%= form.submit :class => "btn btn-success" %>
      </p>
    <% end %><br><br>
    <%= button_to 'Back', questions_path, method: :get, class: "btn btn-info" %>
  </center><br>
</body>
</html>

app/views/questions/show.html.erb
<html>
  <head>
  </head>
  <body>
    <div id="back_button">
      <%= button_to 'Back', questions_path, method: :get, class: "btn btn-info", :id => "back_button_id" %>
    </div>
    <div class="question_body">
      <h2><%= @question.title %></h2>
      <span>Asked </span><b><%= time_ago_in_words(@question.created_at.strftime("%b %d, %Y at %I:%M")) %> ago</b>
      <span class="last_answered">Last Answered </span><b><%= time_ago_in_words(@question.answers.last(2).first.created_at) %> ago</b>
      <hr>
      <span id="question_description"><%= @question.description.html_safe %></span><br><br>
      <span class="question_time"><%= @question.created_at.strftime("%b %d, %Y at %I:%M") %></span><br>
      <span class="questioner_name"><b>@ <%= questioner_name(@question) %></b></span><br><br><hr class="question_line">
    </div><br>

    <div class="container">
      <ul class="nav nav-tabs" id="answer_tabs">
        <li class="active"><a data-toggle="tab" href="#aactive">Active</a></li>
        <li><a data-toggle="tab" href="#oldest">Oldest</a></li>
        <li><a data-toggle="tab" href="#votes">Votes</a></li>
        <li><span id="total_answeres"><%= @answers.count %> <%= @answers.count <= 1 ? 'Answer' : 'Answers' %></span></li>
      </ul>

      <div class="tab-content">
        <div id="aactive" class="tab-pane fade in active">
          <div class="jumbotron">
            <% @active_answers.each do |answer| %><br>
              <div class="answer_box">
                <div class="box_row">
                  <div class="box_cell box1">
                    <%= link_to '<i class="fas fa-caret-up" id="like_button"></i>'.html_safe, like_dislike_answer_path(answer, 'like'), method: :put, remote: :true %><br>
                    <div class="total_likes"><%= answer.get_likes.size - answer.get_dislikes.size %></div>
                    <%= link_to '<i class="fas fa-caret-down" id="dislike_button"></i>'.html_safe, like_dislike_answer_path(answer, 'dislike'), method: :put, remote: :true %>
                  </div><br>
                  <div class="box_cell box2">
                    <% if answer.description.html_safe.length > 200 %>
                      <%= truncate(answer.description.html_safe, length: 200) %>
                      <%= link_to '...Read more', '', class: "read-more-#{answer.id}" %>
                      <script>
                        $('.read-more-<%= answer.id %>').on('click', function(e) {
                          e.preventDefault()
                          $(this).parent().html('<%= escape_javascript answer.description.html_safe %>')
                        })
                      </script>
                    <% else %>
                      <%= answer.description.html_safe %>
                    <% end %>

                    <br><br>
                    <span class="answer_time"><%= answer.created_at.strftime("%b %d, %Y at %I:%M") %></span><br>
                    <span class="answerer_name"><b>@ <%= answerer_name(answer) %></b></span><br><br><hr class="comment_line">
                    <% answer.comments.each do |comment| %>
                      <ul class="comment_list">
                        <li>
                          <span class="comment_discription"><%= comment.description %> - 
                          <span class="commenter_name"><b>@ <%= commenter_name(comment) %>,</b></span>
                          <span class="comment_time"><%= comment.created_at.strftime("%b %d, %Y at %I:%M") %></span>
                        </li><hr class="comment_line">
                      </ul>
                    <% end %>
                    <a id="comment_link">reply</a>
                    <div class="comment_form_class">
                      <br><%= render partial: 'comment_form', locals: {:answer => answer, :comment => @comment, :question => @question} %>
                    </div>
                  </div>
                </div>
              </div><br><hr class="comment_line">
            <% end %>
            <center><%= paginate @active_answers, param_name: "aactive_page" %></center>
          </div>
        </div>
        <div id="oldest" class="tab-pane fade">
          <div class="jumbotron">
            <% @oldest_answers.each do |answer| %><br>
              <div class="answer_box">
                <div class="box_row">
                  <div class="box_cell box1">
                    <%= link_to '<i class="fas fa-caret-up" id="like_button"></i>'.html_safe, like_dislike_answer_path(answer, 'like'), method: :put, remote: :true %><br>
                    <div class="total_likes"><%= answer.get_likes.size - answer.get_dislikes.size %></div>
                    <%= link_to '<i class="fas fa-caret-down" id="dislike_button"></i>'.html_safe, like_dislike_answer_path(answer, 'dislike'), method: :put, remote: :true %>
                  </div><br>
                  <div class="box_cell box2">
                    <% if answer.description.html_safe.length > 200 %>
                      <%= truncate(answer.description.html_safe, length: 200) %>
                      <%= link_to '...Read more', '', class: "read-more-#{answer.id}" %>
                      <script>
                        $('.read-more-<%= answer.id %>').on('click', function(e) {
                          e.preventDefault()
                          $(this).parent().html('<%= escape_javascript answer.description.html_safe %>')
                        })
                      </script>
                    <% else %>
                      <%= answer.description.html_safe %>
                    <% end %>

                    <br><br>
                    <span class="answer_time"><%= answer.created_at.strftime("%b %d, %Y at %I:%M") %></span><br>
                    <span class="answerer_name"><b>@ <%= answerer_name(answer) %></b></span><br><br><hr class="comment_line">
                    <% answer.comments.each do |comment| %>
                      <ul class="comment_list">
                        <li>
                          <span class="comment_discription"><%= comment.description %> - 
                          <span class="commenter_name"><b>@ <%= commenter_name(comment) %>,</b></span>
                          <span class="comment_time"><%= comment.created_at.strftime("%b %d, %Y at %I:%M") %></span>
                        </li><hr class="comment_line">
                      </ul>
                    <% end %>
                    <a id="comment_link">reply</a>
                    <div class="comment_form_class">
                      <br><%= render partial: 'comment_form', locals: {:answer => answer, :comment => @comment, :question => @question} %>
                    </div>
                  </div>
                </div>
              </div><br><hr class="comment_line">
            <% end %>
            <center><%= paginate @oldest_answers, param_name: "oldest_page" %></center>
          </div>
        </div>
        <div id="votes" class="tab-pane fade">
          <div class="jumbotron">
            <% @answers_votes.each do |answer| %><br>
              <div class="answer_box">
                <div class="box_row">
                  <div class="box_cell box1">
                    <%= link_to '<i class="fas fa-caret-up" id="like_button"></i>'.html_safe, like_dislike_answer_path(answer, 'like'), method: :put, remote: :true %><br>
                    <div class="total_likes"><%= answer.get_likes.size - answer.get_dislikes.size %></div>
                    <%= link_to '<i class="fas fa-caret-down" id="dislike_button"></i>'.html_safe, like_dislike_answer_path(answer, 'dislike'), method: :put, remote: :true %>
                  </div><br>
                  <div class="box_cell box2">
                    <% if answer.description.html_safe.length > 200 %>
                      <%= truncate(answer.description.html_safe, length: 200) %>
                      <%= link_to '...Read more', '', class: "read-more-#{answer.id}" %>
                      <script>
                        $('.read-more-<%= answer.id %>').on('click', function(e) {
                          e.preventDefault()
                          $(this).parent().html('<%= escape_javascript answer.description.html_safe %>')
                        })
                      </script>
                    <% else %>
                      <%= answer.description.html_safe %>
                    <% end %>

                    <br><br>
                    <span class="answer_time"><%= answer.created_at.strftime("%b %d, %Y at %I:%M") %></span><br>
                    <span class="answerer_name"><b>@ <%= answerer_name(answer) %></b></span><br><br><hr class="comment_line">
                    <% answer.comments.each do |comment| %>
                      <ul class="comment_list">
                        <li>
                          <span class="comment_discription"><%= comment.description %> - 
                          <span class="commenter_name"><b>@ <%= commenter_name(comment) %>,</b></span>
                          <span class="comment_time"><%= comment.created_at.strftime("%b %d, %Y at %I:%M") %></span>
                        </li><hr class="comment_line">
                      </ul>
                    <% end %>
                    <a id="comment_link">reply</a>
                    <div class="comment_form_class">
                      <br><%= render partial: 'comment_form', locals: {:answer => answer, :comment => @comment, :question => @question} %>
                    </div>
                  </div>
                </div>
              </div><br><hr class="comment_line">
            <% end %>
            <center><%= paginate @answers_votes, param_name: "votes_page" %></center>
          </div>
        </div>
      </div>
    </div>

    <center>
      <div id="render_answer_form" >
        <%= render partial: 'answer_form', locals: {:question => @question, :answer => @answer } %>
      </div>
    </center>
  </body>
</html>